services:
  - type: web
    name: nikky
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn NICKY_COSMETICS.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: NICKY_COSMETICS.settings
      - key: SECRET_KEY
        value: django-insecure-1a2u!a$o*gno%r^4k*6xz@j3sg0ci%$s9=cubhvx1-)+o5*te@
